steps:
  - name: gcr.io/cloud-builders/docker
    entrypoint: bash
    args:
      - -c
      - docker pull "${_CACHE_IMAGE}" || true

  - name: gcr.io/cloud-builders/docker
    args:
      - build
      - --cache-from
      - ${_CACHE_IMAGE}
      - -t
      - ${_IMAGE}
      - -t
      - ${_CACHE_IMAGE}
      - .

  - name: gcr.io/cloud-builders/docker
    entrypoint: bash
    args:
      - -c
      - if [ "${_CACHE_IMAGE}" != "${_IMAGE}" ]; then docker push "${_CACHE_IMAGE}"; fi

images:
  - ${_IMAGE}

serviceAccount: projects/chm-network/serviceAccounts/chm-build-sa@chm-network.iam.gserviceaccount.com

options:
  logging: CLOUD_LOGGING_ONLY

substitutions:
  _IMAGE: us-east4-docker.pkg.dev/chm-network/chm-apps/chm:latest
  _CACHE_IMAGE: us-east4-docker.pkg.dev/chm-network/chm-apps/chm:latest
