steps:
  - name: gcr.io/cloud-builders/docker
    args:
      - build
      - -t
      - ${_IMAGE}
      - .

images:
  - ${_IMAGE}

serviceAccount: projects/chm-network/serviceAccounts/chm-build-sa@chm-network.iam.gserviceaccount.com

options:
  logging: CLOUD_LOGGING_ONLY

substitutions:
  _IMAGE: us-east4-docker.pkg.dev/chm-network/chm-apps/chm:latest
